language: python
dist: bionic
cache: pip

before_script:
  - pip install tox

script: tox

matrix:
  include:

    - python: "3.9"
      env: TOXENV=py39

    - python: "3.10"
      env: TOXENV=py310

notifications:
  email: false
