name: Test

on:
  pull_request:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install tox
        run: pip install tox

      - name: Run tox 3.9
        if: ${{ matrix.python-version }} == "3.9"
        env:
          TOXENV: py39

      - name Run tox 3.10
        if: ${{ matrix.python-version }} == "3.9"
        env:
          TOXENV: py310
        run: tox
